### ISSUE TITLE
Staking Issue

### ISSUE THREAD

**Issue by pvincente** [airalab/dapp.robonomics.network#78]
Hi Everyone,

After I migrate my tokens through exodus and I try to stake my Robonomics I get this message?

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read property 'validators' of undefined

TypeError: Cannot read property 'validators' of undefined
at https://polkadot.js.org/apps/main.5249db4c.js:19:739284
at ii (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:362043)
at Ws (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:414092)
at _l (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:401366)
at Pl (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:401294)
at Sl (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:401157)
at ml (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:398144)
at https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:347965
at e.unstable_runWithPriority (https://polkadot.js.org/apps/other.01.8006c99e.js:2:160443)
at $o (https://polkadot.js.org/apps/react.01.2e2ae8a8.js:2:347742)

**Comment by vol4tim** [comment]
This section of the dapp has been redesigned. Please check and open a new issue if you think you have a related issue.
